### ISSUE TITLE
BNLikelihood

### ISSUE THREAD

**Issue by kkatsano** [sdv-dev/SDMetrics#630]
### Environment details

If you are already running SDMetrics, please indicate the following details about the environment in
which you are running it:

* SDMetrics version:0.15.1
* Python version:3.10.14
* Operating System:Ubuntu

### Problem description

I've tried to use BNLikelihood but cannot get it to work even with the installed pomegranate package

### What I already tried

at first I installed the latest version of pomegranate 1.1.0 which failed importing BayesianNetwork as in the latest pomegranate version it is stored under bayesian_network.BayesianNetwork. I tried to downgrade pomegranate to versions 0.14.4 and 0.14.2 but got an istallation error

```
pip install pomegranate==0.14.4
Traceback (most recent call last):
        File "/home/kkatsano/DS/evaluation/evaluation10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/kkatsano/DS/evaluation/evaluation10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/kkatsano/DS/evaluation/evaluation10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-p3eg1msr/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-p3eg1msr/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-p3eg1msr/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-p3eg1msr/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 61, in <module>
        File "/tmp/pip-build-env-p3eg1msr/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-p3eg1msr/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pomegranate/utils.pyx
      [end of output]
```

**Comment by kkatsano** [comment]
I tried the solution proposed in [#701](https://github.com/sdv-dev/SDMetrics/pull/701), however, faced another issue trying to do the following:
pip install sdmetrics[pomegranate]
      Traceback (most recent call last):
        File "/home/kkatsano/DS/evaluation/evaluation10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/home/kkatsano/DS/evaluation/evaluation10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
        File "/home/kkatsano/DS/evaluation/evaluation10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-dk2g5xnv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-dk2g5xnv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-dk2g5xnv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-dk2g5xnv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 61, in <module>
        File "/tmp/pip-build-env-dk2g5xnv/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-dk2g5xnv/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pomegranate/utils.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by npatki** [comment]
Hi @kkatsano, we released an updated version of SDMetrics 2 days ago (version 0.20.1). Would you be able to update and try again?

One other thing to test would be if you are able to install pomegranate on its own (without SDMetrics): `pip install pomegranate` -- if this installation is failing, then it might be some other issue with your platform/Python setup.

If the issue is only occurring when you do `pip install sdmetrics[pomegranate]`, it may still be related to SDMetrics. In this case, would you mind filing a new issue so we can take a look? (As this original one is closed so it's easy to miss.)
